/*drop table OM.OM_INTERFACE_LOGS;
drop sequence INLO_RK_SEQ;
drop trigger INLO_BR_I_TR;
drop trigger INLO_AR_IU_TR;
*/
--**************************************************************************************
--* SQL script to create OM.OM_INTERFACE_LOGS table, primary key, foreign key(s) and indexes. 
--* This table is built based on CAS custom table cascsi.CAS_INTERFACE_LOGS
--* Revision Log
--* Version#   Date        FogBugz#    Revision Description                   Revised By
--* 01         2016-11-07              Created the script                     James Jose
--**************************************************************************************
create table OM.OM_INTERFACE_LOGS
(
  INLO_RK                 NUMBER(9) not null,  
  RUN_ID                  VARCHAR2(100),
  LOG_ENTRY_TYPE          VARCHAR2(240),
  APPLICATION_NAME        VARCHAR2(100),
  PACKAGE_NAME            VARCHAR2(100),
  PROCEDURE_NAME          VARCHAR2(100),
  PARAMETER_VALUE         VARCHAR2(240),
  KEY1_ID                 VARCHAR2(100),
  KEY2_ID                 VARCHAR2(100),
  LOG_TEXT                VARCHAR2(1000),
  CRE_USER                VARCHAR2(30) not null,
  CRE_SRC                 VARCHAR2(100) not null,
  CRE_TMSTMP              TIMESTAMP(6) not null,
  UPD_USER                VARCHAR2(30) not null,
  UPD_SRC                 VARCHAR2(100) not null,
  UPD_TMSTMP              TIMESTAMP(6) not null)

  tablespace OMDATA;
 --Add comments on table and columns  
comment on table OM.OM_INTERFACE_LOGS is 'Used to store the acknowledgement that an individual has confirmed receipt of their service. This table is similar to cascsi.CAS_INTERFACE_LOGS table in CAS.';
comment on column OM.OM_INTERFACE_LOGS.INLO_RK is 'A unique system generated identifier for OM_INTERFACE_LOGS.'; 
comment on column OM.OM_INTERFACE_LOGS.RUN_ID is 'Run that this log entry applies to';
comment on column OM.OM_INTERFACE_LOGS.LOG_ENTRY_TYPE is 'Logging Severty';
comment on column OM.OM_INTERFACE_LOGS.APPLICATION_NAME is 'Application that generated the log entry';
comment on column OM.OM_INTERFACE_LOGS.PACKAGE_NAME is 'Package that generated the log entry';
comment on column OM.OM_INTERFACE_LOGS.PROCEDURE_NAME is 'Procedure that generated the log entry';
comment on column OM.OM_INTERFACE_LOGS.PARAMETER_VALUE is 'Any parameter values';
comment on column OM.OM_INTERFACE_LOGS.KEY1_ID is 'Optional keys included for context in log entry';
comment on column OM.OM_INTERFACE_LOGS.KEY2_ID is 'Optional keys included for context in log entry';
comment on column OM.OM_INTERFACE_LOGS.LOG_TEXT is 'Interface log description generated by the process';
comment on column OM.OM_INTERFACE_LOGS.CRE_USER is 'Userid of the user who created the record.';           
comment on column OM.OM_INTERFACE_LOGS.CRE_SRC is 'The identifier of the system or system component that created the record.';              
comment on column OM.OM_INTERFACE_LOGS.CRE_TMSTMP is 'The date, time (with fractions of seconds) when the record was created.';          
comment on column OM.OM_INTERFACE_LOGS.UPD_USER is 'Userid of the user who last updated the record.';             
comment on column OM.OM_INTERFACE_LOGS.UPD_SRC is  'The identifier of the system or system component that last updated the record.';             
comment on column OM.OM_INTERFACE_LOGS.UPD_TMSTMP is 'The date, time (with fractions of seconds) when the record was last updated.';  

--Add Constraints
--Primary key
alter table OM.OM_INTERFACE_LOGS
  add constraint INLO_PK primary key (INLO_RK)
  using index tablespace OMIDX;
  
/*prompt
prompt Creating sequence INLO_RK_SEQ
prompt =============================
prompt*/
create sequence OM.INLO_RK_SEQ
minvalue 1
maxvalue 9999999999999999999999999999
start with 1
increment by 1
cache 20;

create sequence OM.INLO_RUN_ID_SEQ
minvalue 1
maxvalue 9999999999999999999999999999
start with 1
increment by 1
cache 20;

/*prompt
prompt Creating trigger INLO_BR_I_TR
prompt ===============================
prompt*/
--Following logic is moved to om_interface_logs.fn_next_inlo_rk
/*CREATE OR REPLACE TRIGGER OM.INLO_BR_I_TR
 BEFORE INSERT
 ON OM.OM_INTERFACE_LOGS
 FOR EACH ROW
begin
  if :new.INLO_RK is null
  then
    select INLO_RK_seq.nextval
    into  :new.INLO_RK
    from dual;
  end if;
end;
/
*/
/*prompt
prompt Creating trigger INLO_AR_IU_TR
prompt ===============================
prompt*/
CREATE OR REPLACE TRIGGER OM.INLO_AR_IU_TR
 BEFORE INSERT OR UPDATE
 ON OM.OM_INTERFACE_LOGS
 FOR EACH ROW
BEGIN
  IF inserting
  THEN
    :new.cre_user := USER;
    IF :new.cre_src IS NULL
    THEN
      :new.cre_src := pkg_audit.fnc_get_transaction_source(:new.upd_src,:old.upd_src);
    END IF;
    :new.cre_tmstmp := current_timestamp;
    :new.upd_user   := :new.cre_user;
    :new.upd_src    := :new.cre_src;
    :new.upd_tmstmp := :new.cre_tmstmp;
  ELSIF updating
  THEN
    :new.cre_user   := :old.cre_user;
    :new.cre_src    := :old.cre_src;
    :new.cre_tmstmp := :old.cre_tmstmp;
    :new.upd_user   := USER;
    :new.upd_tmstmp := current_timestamp;

    --If new and old have the same value, and the columns was not
    --explicitly updated then overide with the value from the function
    IF (:new.upd_src = :old.upd_src AND NOT updating('upd_src'))
       OR :new.upd_src IS NULL
    THEN
      :new.upd_src := pkg_audit.fnc_get_transaction_source(:new.upd_src,:old.upd_src);
    END IF;

  END IF;
END;
/
create or replace public synonym OM_INTERFACE_LOGS FOR OM.OM_INTERFACE_LOGS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON OM.OM_INTERFACE_LOGS TO OMSERVICE WITH GRANT OPTION;
